######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 28 15:52:22 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp callgrindtester.cpp
HEADERS += callgrindtester.h
