#!/bin/sh

# This script builds the headless bdiana version as a Debian package.
# (The headless version is the one that depends on QWS rather than on X11.)

metno-debuild -eMETNO_CONFIG=precise_headless -b -us -uc -j7
