#!/bin/sh

# This script builds a Debian package of the bdiana version that depends
# on QWS (rather than on X11).

set -e # Exit on first failure

metno-debuild -eMETNO_CONFIG=precise_headless -b -us -uc -j7
