#!/bin/sh

# This script builds and installs the bdiana version that depends on X11.

set -e # Exit on first failure

install_dir=$WORKSPACE/install
mkdir -p $install_dir
rm -rf $install_dir/*
./autogen.sh
./configure \
  PKG_CONFIG_PATH=$JENKINS_HOME/jobs/metlibs_build/workspace/install/lib/pkgconfig \
  --prefix=$install_dir \
  --enable-batch-only
make clean
make -j7
make check
make install
