#!/bin/sh

# This script builds metlibs as a Debian package.

set -e # Exit on first failure

metno-debuild -b -us -uc # ### Add back -j7 option once we have resolved race condition related to omniidl
