#!/bin/sh

# This script installs the Debian packages built from metlibs.

set -e # Exit on first failure
set -x

cd upstream_artifacts

# NOTE: To avoid missing dependencies when installing packages below,
# packages in Level i must be installed before packages in
# Level i + 1.

# Level 1
echo installing Level 1 ...
for p in \
  metlibs-libmi-dev_*_amd64.deb \
  metlibs-pods-dev_*_amd64.deb \
  metlibs-glp-dev_*_amd64.deb \
  metlibs-milogger-dev_*_amd64.deb \
  metlibs-miftgl-dev_*_amd64.deb \
  metlibs-pgconpool-dev_*_amd64.deb \
  metlibs-putools-dev_*_amd64.deb
do dpkg -i $p
done

# Level 2
echo installing Level 2 ...
for p in \
  metlibs-milib-dev_*_amd64.deb \
  metlibs-puctools-dev_*_amd64.deb \
  metlibs-pumet-dev_*_amd64.deb \
  metlibs-pusql-dev_*_amd64.deb \
  metlibs-propoly-dev_*_amd64.deb \
  metlibs-gltext-dev_*_amd64.deb
do dpkg -i $p
done

# Level 3
echo installing Level 3 ...
for p in \
  metlibs-difield-dev_*_amd64.deb \
  metlibs-dimitiff-dev_*_amd64.deb \
  metlibs-disql-dev_*_amd64.deb \
  metlibs-parameter-dev_*_amd64.deb \
  metlibs-qutilities-dev_*_amd64.deb
do dpkg -i $p
done

# Level 4
echo installing Level 4 ...
for p in \
  metlibs-pudatatypes-dev_*_amd64.deb \
  metlibs-robs-dev_*_amd64.deb \
  metlibs-profunctions-dev_*_amd64.deb
do dpkg -i $p
done

# Level 5
echo installing Level 5 ...
for p in \
  metlibs-profet-dev_*_amd64.deb \
  metlibs-tsdata-dev_*_amd64.deb
do dpkg -i $p
done

# Level 6
echo installing Level 6 ...
for p in \
  metlibs-pets2-dev_*_amd64.deb
do dpkg -i $p
done

# Level 7
echo installing Level 7 ...
for p in \
  metlibs-qtimeseries-dev_*_amd64.deb
do dpkg -i $p
done
