#!/bin/sh

# This script builds a Debian package of the bdiana version that depends
# on QWS (rather than on X11) and is configured with Perl.

set -e # Exit on first failure
set -x

metno-debuild -eMETNO_CONFIG=precise_headless -b -us -uc -j7

# Keep artifacts inside the workspace, otherwise Jenkins won't find them
mkdir artifacts
mv ../libmetno-bdiana-perl*.deb artifacts
