#!/bin/sh

# This script installs the Debian package built from the bdiana version
# that depends on QWS (rather than on X11) and is configured with Perl.

set -e # Exit on first failure
set -x

cd upstream_artifacts

# TODO: Remove dependencies to version number in the command below
# (plus ensure that there is exactly one .deb files etc.):
dpkg -i libmetno-bdiana-perl_3.29.2-0_amd64.deb
