#!/bin/sh

# This script installs the Debian package for the WMS server.

set -e # Exit on first failure
set -x

apt-get install cgi-mapserver=6.0.1-3metno1

mkdir debs
cd debs
cp metno-wmsserver*.deb .

dpkg-scanpackages . /dev/null | gzip -c -9 > Packages.gz
cat >> /etc/apt/sources.list << EOF

deb file://$PWD /
EOF

apt-get update

apt-get install metno-wmsserver
