######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 12 09:09:03 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

CONFIG += debug
